### ISSUE TITLE
Documentation/screenshots?

### ISSUE THREAD

**Issue by brylie** [Tonejs/ui#11]
Related to #4 

Please add some documentation for this project, as it might be generally useful as a library for other projects :-)

**Comment by stephaneeybert** [comment]
I agree. As of now I'm totally unable to even start making use of it. Too bad. I would be glad to see how to create multiple simple keyboards on a page and attach a synth to each of them.

**Comment by rohithandique** [comment]
Agree! I'd love to use these UI elements instead of other libraries or writing them from scratch. It would really help me in my projects!

**Comment by tambien** [comment]
Thanks for the issue and your interest. The intention of the project (i'll try to clarify on the README) is not to support another library, but just to show the internal workings of the Tone.js examples for those who are curious and to give an example of building GUIs with Tone.js.
