### ISSUE TITLE
Is there Documentation?

### ISSUE THREAD

**Issue by joelmartinez** [Tonejs/ui#4]
I can't really find any information about this library, aside from a reference/link to tonejs UI in the examples readme:  
https://github.com/Tonejs/Tone.js/blob/master/examples/README.md

Is there any documentation, or other resources for using this library? or is it expected that this is only to service the tonejs documentation?

Mainly trying to check and see if there's anything else before I dive into trying to understand the sample code (or build something myself) :)

**Comment by tambien** [comment]
Unfortunately there is no other documentation for this. Currently it's just meant to show the code that i used to create the Tone.js examples page.

**Comment by joelmartinez** [comment]
@tambien ok ... I will use them as a learning resource and build my own. Thanks!
